name: Compile and Deploy LaTeX Document
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetches all history for all branches and tags

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: techCV.tex  # Your LaTeX file name
          compiler: xelatex  # Change this to xelatex or lualatex
          args: -file-line-error -halt-on-error -interaction=nonstopmode

      - name: Commit and Push PDF
        run: |
          mkdir -p docs
          cp techCV.pdf docs/techCV.pdf  # Copy the PDF to the docs folder
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/techCV.pdf
          git commit -m "Update PDF in docs folder"
          git push https://alicehamberger:${{ secrets.GH_PAT }}@github.com/alicehamberger/tech-CV.git
