name: Compile LaTeX Document
on:
  push:
    branches:
      - main  # or your default branch name
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: your-document.tex  # Replace with your main LaTeX file name
